server: 
  port: 8080
spring:
  http: 
    encoding: 
      charset: UTF-8
      enable: true
      force: true
  mvc: 
    #出现错误直接抛出异常
    throw-exception-if-no-handler-found: true
    #不要为资源文件建立映射
  resources:
    add-mappings: false
  datasource:
    name: demo
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: localhost
    port: 6379
    password: 
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: / 
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.study.demo.entity
fileServer:
  dir: f://files// 
exportTemplate:
  dir: f://template//  
  temp: f://temp// 
  
   
  